language: php
php:
  - 5.5
  - 5.4
  - 5.3
install:
  - pear install pear/PHP_CodeSniffer pear/http_request2 pear/cache_lite pear/crypt_diffiehellman-beta pear/services_yadis-beta pear/net_url2 pear/log pear/mdb2 pear/http_oauth-alpha
  - phpenv rehash
script:
  - phpcs -n OpenID*
  - cd tests && phpunit .
