language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
install:
  - pear upgrade -f pear
  - pear install Crypt_DiffieHellman-beta Services_Yadis-beta
  - pear install --alldeps package.xml
  - wget https://phar.phpunit.de/phpunit-5.7.phar
  - phpenv rehash
script:
  - php phpunit-5.7.phar tests/
