language: php
install:
  - pear upgrade -f pear
  - pear install php_codesniffer
  - pear install Crypt_DiffieHellman-beta Services_Yadis-beta
  - pear install --alldeps package.xml
  - wget https://phar.phpunit.de/phpunit-5.7.phar
php:
  - 5.6
  - 7.0
  - 7.1
sudo: false
script:
  - cd tests && tar -xzf ./fixtures.tar.gz
  - cd .. && php phpunit-5.7.phar tests/
  - phpenv rehash
script:
  - phpcs -n OpenID*
  - php phpunit-5.7.phar tests/
